function Hd = getFilter
%GETFILTER Returns a discrete-time filter System object.

% MATLAB Code
% Generated by MATLAB(R) 9.4 and DSP System Toolbox 9.6.
% Generated on: 17-May-2019 14:43:59

N    = 2;    % Order
F3dB = 4;    % 3-dB Frequency
Fs   = 500;  % Sampling Frequency

h = fdesign.highpass('n,f3db', N, F3dB, Fs);

Hd = design(h, 'butter', ...
    'SystemObject', true);


